### ISSUE TITLE
Cargolifter don't work

### ISSUE THREAD

**Issue by Robbio69** [Mailbutler/evernote-exporter-mail-plugin#6]
Good evening,

With the upgrade to Catalina, CargoLifter even if installed and logged in with Google Drive, does not transfer attachments to the cloud. Help!

Roberto

**Comment by Ute-Lab** [comment]
Problem CargoLifter (Installer_53)
CargoLifter does not accept large files. Accepts only files up to 35MB. So it's useless.Before I could upload very heavy files.I did the test sending a file less heavy than 35MB and it works. 
Please arrange, otherwise it is useless to use cargolifter. 
This happens both for uploading to DropBox and for GoogleDrive.
Thanks! 
![error_cargolifter](https://user-images.githubusercontent.com/56894241/67327326-0ac1bd00-f518-11e9-86b3-cf57656575a7.png)

**Comment by fjaeger** [comment]
This project is about Evernote Exporter.

**Comment by Ute-Lab** [comment]
Good morning,
first I apologize if I wrote where I didn't have to.
I'm not familiar with your site.
Can you open a new topic for CargoLifter that no longer works with MacOS High Sierra and Catalina Mail if the dimensions exceed 35MB?
I'm sorry but Mailbulter's support has written me to address you.
Thank you so much if you can help me.

Roberta

**Comment by fjaeger** [comment]
The red warning text that you are seeing does not come from CargoLifter, but directly from Mail.

**Comment by Ute-Lab** [comment]
OK, but if I have activated the uploading of files through CargoLifter, it should be able (as it has always been in the past) to upload the files to DropBox or GoogleDrive (for DrobBox, for example, the message is as in screen, which I re-attach) .
Now you can no longer upload to external "clouds".

Generally Mail attachments can be uploaded if they are less than 25MB, not 35.

Sorry, even my bad English. I'm using a translator.
And sorry if I bother you :-)

**Comment by Ute-Lab** [comment]
For completeness, I send you the reply from Mailbutler support.

Roberta
